### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by bernisnukic** [cloudflare-apps/create-cloudflare-app#2]
When doing a `yarn install` it tries to install event-stream 3.3.6 which was recently removed from npm:

https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident

It also tries to install flatmap-stream which was also removed so the installation fails.

**Comment by mpint** [comment]
Thanks for this info @bernisnukic.  I've updated the yarn.lock file.  Can you pull down the latest and try installing again?
