### ISSUE TITLE
Latest Release

### ISSUE THREAD

**Issue by oleteacher** [cloudflare-apps/create-cloudflare-app#51]
https://github.com/CloudflareApps/CreateCloudflareApp/releases/latest = 404 page?

No way to compile for week or so and wanted to get started on creating an app.

**Comment by SimJoSt** [comment]
You are missing the dashes `-` in the url: `https://github.com/Cloudflare-Apps/Create-Cloudflare-App/releases/latest`

**Comment by oleteacher** [comment]
@SimJoSt Now I feel like a big dummy ;)

Thanks!
